language: python
matrix:
  include:
    - python: 3.6
      dist: xenial
      sudo: true

services:
  - sqlite3

env:
  - DJANGO=3.1

before_install:
  - export DJANGO_SETTINGS_MODULE=BRT.settings
  - export PYTHONPATH=$HOME/builds/NonsoAmadi10/BRT
  - pip install virtualenv
  - virtualenv brt
install:
  - pip install -r requirements.txt

script:
  - sh ./build.sh
