# Generated by Django 3.1.4 on 2020-12-19 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0004_trip_status'),
        ('bookings', '0005_auto_20201219_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='BRT-4m0K7tiVjZUb', max_length=155),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
