# Generated by Django 3.1.4 on 2020-12-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20201219_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='BRT-NDr2uvgcVnDS', max_length=155),
        ),
    ]
