# Generated by Django 3.1.4 on 2020-12-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20201216_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='curr_capacity',
        ),
        migrations.AddField(
            model_name='trip',
            name='curr_bus_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
